# Generated by Django 5.1.1 on 2025-05-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0002_remove_productimage_image_url_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
