# Generated by Django 5.1.1 on 2025-05-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0003_blogpost_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('location', 'Location'), ('email', 'Email'), ('phone', 'Phone'), ('facebook', 'Facebook'), ('tiktok', 'Tiktok'), ('instagram', 'Instagram')], default='location', max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thông tin liên hệ',
                'verbose_name_plural': 'Thông tin liên hệ',
            },
        ),
    ]
