# Generated by Django 5.1.1 on 2025-05-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0004_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
