# Generated by Django 5.1.1 on 2025-05-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0005_contactinfo_name_alter_contactinfo_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slides/')),
                ('link', models.URLField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['sort_order'],
            },
        ),
    ]
