# Generated by Django 5.1.1 on 2025-05-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0006_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='type',
            field=models.CharField(choices=[('location', 'Location'), ('email', 'Email'), ('phone', 'Phone'), ('facebook', 'Facebook'), ('tiktok', 'Tiktok'), ('instagram', 'Instagram'), ('zalo', 'Zalo')], default='location', max_length=20),
        ),
    ]
