# Generated by Django 5.1.1 on 2025-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0007_blogpost_description_alter_contactinfo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/'),
        ),
    ]
