# Generated by Django 5.1.1 on 2025-05-09 04:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decor", "0011_remove_product_categories_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="phone_number",
            field=models.CharField(max_length=20, blank=True),
        ),
    ]
