# Generated by Django 5.1.1 on 2025-05-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decor", "0012_remove_contactmessage_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
