# Generated by Django 5.1.1 on 2025-05-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decor", "0013_alter_contactmessage_message_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='contactmessage',
        #     name='email',
        # ),
    ]
