# Generated by Django 5.1.1 on 2025-05-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0016_remove_contactmessage_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
