# Generated by Django 5.1.1 on 2025-05-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decor", "0018_remove_contactmessage_subject"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='contactmessage',
        #     name='subject',
        # ),
    ]
