# Generated by Django 5.1.1 on 2025-05-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0019_remove_contactmessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
