# Generated by Django 5.1.1 on 2025-05-09 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0020_contactmessage_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='email',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
