# Generated by Django 5.1.1 on 2025-05-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0021_rename_email_contactmessage_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('credentials_file', models.FileField(upload_to='credentials/')),
                ('spreadsheet_id', models.CharField(help_text='Google Sheet ID', max_length=100)),
            ],
        ),
    ]
