# Generated by Django 5.1.1 on 2025-05-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0022_googleserviceaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Hình ảnh sản phẩm (Size: 800 x 800px)', 'verbose_name_plural': 'Hình ảnh sản phẩm (Size: 800 x 800px)'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['-id'], 'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Size: 450 x 450px', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Size: 800 x 800px', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(help_text='Size: 1920 x 742 px', upload_to='slides/'),
        ),
    ]
