# Generated by Django 5.1.1 on 2025-05-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0023_trackingcode_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.ImageField(blank=True, help_text='Size: 1200 x 630 px', null=True, upload_to='thumbnail/')),
                ('url', models.CharField(blank=True, max_length=255)),
                ('siteName', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Thông tin website',
                'verbose_name_plural': 'Thông tin website',
            },
        ),
    ]
